language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
install:
    - pip install -r requirements_tests.txt --use-mirrors
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 --use-mirrors; fi"
script:
    - tests/run_tests.sh
notifications:
    email:
        - deniscostadsc@gmail.com
after_success:
  - coveralls --ignore-errors